### PR TITLE
Fixing various issues in python3 port

### PR DESCRIPTION
**Pull request by timgkeller**
Fixed all test errors

### CODE REVIEW

**Comment by timgkeller** [comment]
Checks probably failed as the CI is still configured to run with Python 2

**Comment by dlindquist** [comment]
@abulka would it be possible for you to take a look at this as it relates to #104 ?

**Comment by dlindquist** [comment]
@timgkeller - would it be possible to update https://github.com/hulu/restfulgit/blob/master/.travis.yml#L3 as part of this PR, or do you think it should be done in a different PR?

**Comment by timgkeller** [comment]
> @timgkeller - would it be possible to update
> 
> https://github.com/hulu/restfulgit/blob/142307681557e00892f1d5b8b0fd894a0bd3abb3/.travis.yml#L3
> 
> as part of this PR, or do you think it should be done in a different PR?

I can adapt this in this pull request, but I won't be able to do it before Sunday. Some other adaptions are also necessary for the script, e.g. updating the libgit version. There are also some pylint and PEP8 issues I'd like to fix while I'm on it. Do you mind using 120 characters per line as a configuration?

**Comment by dlindquist** [comment]
@timgkeller - Sorry for not getting back earlier in the week.  This change looks good now, thank you very much for the contribution!

> Do you mind using 120 characters per line as a configuration?

That would be my preference as well.  

Removing the style checks is okay for now.  I'll rebase the changes as they are - it's a good step forward!

**Pull request merged**
